<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class AlumniSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('alumnis')->insert([
        [
                'nama' => 'Radith Yafi Valerian',
                'nim' => '2021101001',
                'prodi' => 'Teknik Komputer',
                'tahun_masuk' => 2021,
                'tahun_lulus' => 2025,
                'IPK' => 3.3,
                'email' => 'radith01@example.com',
                'no_hp' => '081440961582',
                'pekerjaan' => 'Software Developer',
                'instansi' => 'Teknologi Mandiri',
                'alamat' => 'Jl. Mawar No. 97, Surabaya',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Bima Setya Ramadhan',
                'nim' => '2021101002',
                'prodi' => 'Sistem Informasi',
                'tahun_masuk' => 2021,
                'tahun_lulus' => 2025,
                'IPK' => 3.55,
                'email' => 'bimasetya@example.com',
                'no_hp' => '088590710882',
                'pekerjaan' => 'Database Administrator',
                'instansi' => 'Teknologi Mandiri',
                'alamat' => 'Jl. Mawar No. 122, Bandung',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Satria Adi Wijaya',
                'nim' => '2021101003',
                'prodi' => 'Sistem Informasi',
                'tahun_masuk' => 2021,
                'tahun_lulus' => 2025,
                'IPK' => 3.64,
                'email' => 'satriaadi@example.com',
                'no_hp' => '084591525814',
                'pekerjaan' => 'Network Engineer',
                'instansi' => 'Teknologi Mandiri',
                'alamat' => 'Jl. Mawar No. 1, Bandung',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Budi Santoso',
                'nim' => '2021101004',
                'prodi' => 'Sistem Informasi',
                'tahun_masuk' => 2021,
                'tahun_lulus' => 2025,
                'IPK' => 3.49,
                'email' => 'budisantoso@example.com',
                'no_hp' => '089707464712',
                'pekerjaan' => 'Data Analyst',
                'instansi' => 'Teknologi Mandiri',
                'alamat' => 'Jl. Dahlia No. 98, Surabaya',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Citra Lestari',
                'nim' => '2021101005',
                'prodi' => 'Teknik Komputer',
                'tahun_masuk' => 2021,
                'tahun_lulus' => 2025,
                'IPK' => 3.66,
                'email' => 'citralestari@example.com',
                'no_hp' => '084587595946',
                'pekerjaan' => 'Network Engineer',
                'instansi' => 'Teknologi Mandiri',
                'alamat' => 'Jl. Melati No. 71, Surabaya',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Rizky Ramadhan',
                'nim' => '2021101006',
                'prodi' => 'Teknik Komputer',
                'tahun_masuk' => 2021,
                'tahun_lulus' => 2025,
                'IPK' => 3.06,
                'email' => 'rizkyramadhan@example.com',
                'no_hp' => '086573011444',
                'pekerjaan' => 'System Administrator',
                'instansi' => 'Solusi IT Global',
                'alamat' => 'Jl. Melati No. 124, Bandung',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Nina Kartika',
                'nim' => '2021101007',
                'prodi' => 'Sistem Informasi',
                'tahun_masuk' => 2021,
                'tahun_lulus' => 2025,
                'IPK' => 3.09,
                'email' => 'ninakartika@example.com',
                'no_hp' => '089201831223',
                'pekerjaan' => 'Data Analyst',
                'instansi' => 'Solusi IT Global',
                'alamat' => 'Jl. Melati No. 160, Surabaya',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Galih Pratama',
                'nim' => '2021101008',
                'prodi' => 'Informatika',
                'tahun_masuk' => 2021,
                'tahun_lulus' => 2025,
                'IPK' => 3.25,
                'email' => 'galihpratama@example.com',
                'no_hp' => '083861172964',
                'pekerjaan' => 'System Administrator',
                'instansi' => 'Data Insight Co.',
                'alamat' => 'Jl. Mawar No. 31, Surabaya',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Rina Marlina',
                'nim' => '2021101009',
                'prodi' => 'Teknik Komputer',
                'tahun_masuk' => 2021,
                'tahun_lulus' => 2025,
                'IPK' => 3.37,
                'email' => 'rinamarlina@example.com',
                'no_hp' => '082533168387',
                'pekerjaan' => 'Network Engineer',
                'instansi' => 'PT Teknologi Cerdas',
                'alamat' => 'Jl. Kenanga No. 92, Jakarta',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Fajar Nugroho',
                'nim' => '2021101010',
                'prodi' => 'Sistem Informasi',
                'tahun_masuk' => 2021,
                'tahun_lulus' => 2025,
                'IPK' => 3.99,
                'email' => 'fajarnugroho@example.com',
                'no_hp' => '086678486428',
                'pekerjaan' => 'Database Administrator',
                'instansi' => 'Solusi IT Global',
                'alamat' => 'Jl. Anggrek No. 40, Jakarta',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Eka Sari',
                'nim' => '2021101011',
                'prodi' => 'Informatika',
                'tahun_masuk' => 2021,
                'tahun_lulus' => 2025,
                'IPK' => 3.5,
                'email' => 'ekasari@example.com',
                'no_hp' => '087575212827',
                'pekerjaan' => 'Software Developer',
                'instansi' => 'Data Insight Co.',
                'alamat' => 'Jl. Melati No. 146, Bandung',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Yoga Prasetya',
                'nim' => '2021101012',
                'prodi' => 'Sistem Informasi',
                'tahun_masuk' => 2021,
                'tahun_lulus' => 2025,
                'IPK' => 3.37,
                'email' => 'yogaprasetya@example.com',
                'no_hp' => '084768071235',
                'pekerjaan' => 'Software Developer',
                'instansi' => 'Data Insight Co.',
                'alamat' => 'Jl. Mawar No. 176, Bandung',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Ayu Safitri',
                'nim' => '2021101013',
                'prodi' => 'Informatika',
                'tahun_masuk' => 2021,
                'tahun_lulus' => 2025,
                'IPK' => 3.93,
                'email' => 'ayusafitri@example.com',
                'no_hp' => '087721116328',
                'pekerjaan' => 'Database Administrator',
                'instansi' => 'Inovasi Digital Nusantara',
                'alamat' => 'Jl. Kenanga No. 157, Jakarta',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Reza Akbar',
                'nim' => '2021101014',
                'prodi' => 'Teknik Komputer',
                'tahun_masuk' => 2021,
                'tahun_lulus' => 2025,
                'IPK' => 3.76,
                'email' => 'rezaakbar@example.com',
                'no_hp' => '085251005502',
                'pekerjaan' => 'Software Developer',
                'instansi' => 'PT Teknologi Cerdas',
                'alamat' => 'Jl. Dahlia No. 177, Surabaya',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Indah Permata',
                'nim' => '2021101015',
                'prodi' => 'Informatika',
                'tahun_masuk' => 2021,
                'tahun_lulus' => 2025,
                'IPK' => 3.97,
                'email' => 'indahpermata@example.com',
                'no_hp' => '082022994010',
                'pekerjaan' => 'Data Analyst',
                'instansi' => 'Inovasi Digital Nusantara',
                'alamat' => 'Jl. Dahlia No. 97, Surabaya',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Andi Wijaya',
                'nim' => '2021101016',
                'prodi' => 'Teknik Komputer',
                'tahun_masuk' => 2021,
                'tahun_lulus' => 2025,
                'IPK' => 3.62,
                'email' => 'andiwijaya@example.com',
                'no_hp' => '083843776724',
                'pekerjaan' => 'System Administrator',
                'instansi' => 'PT Teknologi Cerdas',
                'alamat' => 'Jl. Melati No. 182, Bandung',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Putri Ayu',
                'nim' => '2021101017',
                'prodi' => 'Informatika',
                'tahun_masuk' => 2021,
                'tahun_lulus' => 2025,
                'IPK' => 3.13,
                'email' => 'putriayu@example.com',
                'no_hp' => '083142922280',
                'pekerjaan' => 'Software Developer',
                'instansi' => 'Inovasi Digital Nusantara',
                'alamat' => 'Jl. Dahlia No. 18, Jakarta',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Dimas Saputra',
                'nim' => '2021101018',
                'prodi' => 'Teknik Komputer',
                'tahun_masuk' => 2021,
                'tahun_lulus' => 2025,
                'IPK' => 3.11,
                'email' => 'dimassaputra@example.com',
                'no_hp' => '084006200016',
                'pekerjaan' => 'System Administrator',
                'instansi' => 'Inovasi Digital Nusantara',
                'alamat' => 'Jl. Dahlia No. 81, Bandung',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Siti Aisyah',
                'nim' => '2021101019',
                'prodi' => 'Informatika',
                'tahun_masuk' => 2021,
                'tahun_lulus' => 2025,
                'IPK' => 3.49,
                'email' => 'sitiaisyah@example.com',
                'no_hp' => '082680574078',
                'pekerjaan' => 'Software Developer',
                'instansi' => 'Data Insight Co.',
                'alamat' => 'Jl. Anggrek No. 126, Surabaya',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Tegar Maulana',
                'nim' => '2021101020',
                'prodi' => 'Sistem Informasi',
                'tahun_masuk' => 2021,
                'tahun_lulus' => 2025,
                'IPK' => 3.58,
                'email' => 'tegarmaulana@example.com',
                'no_hp' => '082187430344',
                'pekerjaan' => 'Database Administrator',
                'instansi' => 'Inovasi Digital Nusantara',
                'alamat' => 'Jl. Melati No. 176, Surabaya',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Lia Novita',
                'nim' => '2021101021',
                'prodi' => 'Teknik Komputer',
                'tahun_masuk' => 2021,
                'tahun_lulus' => 2025,
                'IPK' => 3.13,
                'email' => 'lianovita@example.com',
                'no_hp' => '086933931921',
                'pekerjaan' => 'Database Administrator',
                'instansi' => 'Teknologi Mandiri',
                'alamat' => 'Jl. Melati No. 34, Surabaya',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Arif Rahman',
                'nim' => '2021101022',
                'prodi' => 'Sistem Informasi',
                'tahun_masuk' => 2021,
                'tahun_lulus' => 2025,
                'IPK' => 3.9,
                'email' => 'arifrahman@example.com',
                'no_hp' => '089094151540',
                'pekerjaan' => 'Data Analyst',
                'instansi' => 'Inovasi Digital Nusantara',
                'alamat' => 'Jl. Anggrek No. 24, Jakarta',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Nadia Zahra',
                'nim' => '2021101023',
                'prodi' => 'Sistem Informasi',
                'tahun_masuk' => 2021,
                'tahun_lulus' => 2025,
                'IPK' => 3.41,
                'email' => 'nadiazahra@example.com',
                'no_hp' => '086043927740',
                'pekerjaan' => 'Database Administrator',
                'instansi' => 'Inovasi Digital Nusantara',
                'alamat' => 'Jl. Melati No. 79, Bandung',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Fahmi Hidayat',
                'nim' => '2021101024',
                'prodi' => 'Informatika',
                'tahun_masuk' => 2021,
                'tahun_lulus' => 2025,
                'IPK' => 3.35,
                'email' => 'fahmihidayat@example.com',
                'no_hp' => '087841987494',
                'pekerjaan' => 'Database Administrator',
                'instansi' => 'Teknologi Mandiri',
                'alamat' => 'Jl. Kenanga No. 12, Jakarta',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Yuni Ariska',
                'nim' => '2021101025',
                'prodi' => 'Informatika',
                'tahun_masuk' => 2021,
                'tahun_lulus' => 2025,
                'IPK' => 3.71,
                'email' => 'yuniariska@example.com',
                'no_hp' => '086977422637',
                'pekerjaan' => 'Database Administrator',
                'instansi' => 'Inovasi Digital Nusantara',
                'alamat' => 'Jl. Mawar No. 144, Jakarta',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Bayu Saputra',
                'nim' => '2021101026',
                'prodi' => 'Informatika',
                'tahun_masuk' => 2021,
                'tahun_lulus' => 2025,
                'IPK' => 3.17,
                'email' => 'bayusaputra@example.com',
                'no_hp' => '085285061557',
                'pekerjaan' => 'Software Developer',
                'instansi' => 'PT Teknologi Cerdas',
                'alamat' => 'Jl. Melati No. 108, Surabaya',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Nisa Nuraini',
                'nim' => '2021101027',
                'prodi' => 'Informatika',
                'tahun_masuk' => 2021,
                'tahun_lulus' => 2025,
                'IPK' => 3.41,
                'email' => 'nisanuraini@example.com',
                'no_hp' => '085665537380',
                'pekerjaan' => 'Software Developer',
                'instansi' => 'Data Insight Co.',
                'alamat' => 'Jl. Anggrek No. 129, Surabaya',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Farhan Rizki',
                'nim' => '2021101028',
                'prodi' => 'Sistem Informasi',
                'tahun_masuk' => 2021,
                'tahun_lulus' => 2025,
                'IPK' => 3.92,
                'email' => 'farhanrizki@example.com',
                'no_hp' => '081332910639',
                'pekerjaan' => 'Data Analyst',
                'instansi' => 'PT Teknologi Cerdas',
                'alamat' => 'Jl. Anggrek No. 14, Bandung',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Wulan Anggraini',
                'nim' => '2021101029',
                'prodi' => 'Informatika',
                'tahun_masuk' => 2021,
                'tahun_lulus' => 2025,
                'IPK' => 3.95,
                'email' => 'wulananggraini@example.com',
                'no_hp' => '088615616108',
                'pekerjaan' => 'Database Administrator',
                'instansi' => 'Data Insight Co.',
                'alamat' => 'Jl. Mawar No. 86, Bandung',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Ilham Fauzi',
                'nim' => '2021101030',
                'prodi' => 'Teknik Komputer',
                'tahun_masuk' => 2021,
                'tahun_lulus' => 2025,
                'IPK' => 3.63,
                'email' => 'ilhamfauzi@example.com',
                'no_hp' => '083561647350',
                'pekerjaan' => 'Network Engineer',
                'instansi' => 'Inovasi Digital Nusantara',
                'alamat' => 'Jl. Melati No. 136, Bandung',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Mega Aprilia',
                'nim' => '2021101031',
                'prodi' => 'Teknik Komputer',
                'tahun_masuk' => 2021,
                'tahun_lulus' => 2025,
                'IPK' => 3.72,
                'email' => 'megaaprilia@example.com',
                'no_hp' => '088579059801',
                'pekerjaan' => 'Software Developer',
                'instansi' => 'Data Insight Co.',
                'alamat' => 'Jl. Anggrek No. 3, Bandung',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Riko Prasetyo',
                'nim' => '2021101032',
                'prodi' => 'Informatika',
                'tahun_masuk' => 2021,
                'tahun_lulus' => 2025,
                'IPK' => 3.64,
                'email' => 'rikoprasetyo@example.com',
                'no_hp' => '087546222134',
                'pekerjaan' => 'Software Developer',
                'instansi' => 'PT Teknologi Cerdas',
                'alamat' => 'Jl. Anggrek No. 180, Surabaya',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Dewi Sartika',
                'nim' => '2021101033',
                'prodi' => 'Informatika',
                'tahun_masuk' => 2021,
                'tahun_lulus' => 2025,
                'IPK' => 3.8,
                'email' => 'dewisartika@example.com',
                'no_hp' => '081645730886',
                'pekerjaan' => 'Software Developer',
                'instansi' => 'Inovasi Digital Nusantara',
                'alamat' => 'Jl. Dahlia No. 148, Bandung',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Hendra Kurniawan',
                'nim' => '2021101034',
                'prodi' => 'Sistem Informasi',
                'tahun_masuk' => 2021,
                'tahun_lulus' => 2025,
                'IPK' => 3.99,
                'email' => 'hendrakurniawan@example.com',
                'no_hp' => '084748406266',
                'pekerjaan' => 'Network Engineer',
                'instansi' => 'PT Teknologi Cerdas',
                'alamat' => 'Jl. Anggrek No. 84, Jakarta',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Della Amanda',
                'nim' => '2021101035',
                'prodi' => 'Sistem Informasi',
                'tahun_masuk' => 2021,
                'tahun_lulus' => 2025,
                'IPK' => 3.37,
                'email' => 'dellaamanda@example.com',
                'no_hp' => '081582367428',
                'pekerjaan' => 'System Administrator',
                'instansi' => 'Inovasi Digital Nusantara',
                'alamat' => 'Jl. Melati No. 34, Bandung',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Agus Salim',
                'nim' => '2021101036',
                'prodi' => 'Teknik Komputer',
                'tahun_masuk' => 2021,
                'tahun_lulus' => 2025,
                'IPK' => 3.24,
                'email' => 'agussalim@example.com',
                'no_hp' => '081292692277',
                'pekerjaan' => 'Network Engineer',
                'instansi' => 'Solusi IT Global',
                'alamat' => 'Jl. Kenanga No. 59, Bandung',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Salsa Amelia',
                'nim' => '2021101037',
                'prodi' => 'Sistem Informasi',
                'tahun_masuk' => 2021,
                'tahun_lulus' => 2025,
                'IPK' => 3.89,
                'email' => 'salsaamelia@example.com',
                'no_hp' => '089978619002',
                'pekerjaan' => 'Network Engineer',
                'instansi' => 'Teknologi Mandiri',
                'alamat' => 'Jl. Mawar No. 51, Surabaya',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Ryan Pradana',
                'nim' => '2021101038',
                'prodi' => 'Teknik Komputer',
                'tahun_masuk' => 2021,
                'tahun_lulus' => 2025,
                'IPK' => 3.92,
                'email' => 'ryanpradana@example.com',
                'no_hp' => '087679572843',
                'pekerjaan' => 'Network Engineer',
                'instansi' => 'Data Insight Co.',
                'alamat' => 'Jl. Dahlia No. 14, Surabaya',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Tiara Kusuma',
                'nim' => '2021101039',
                'prodi' => 'Sistem Informasi',
                'tahun_masuk' => 2021,
                'tahun_lulus' => 2025,
                'IPK' => 3.78,
                'email' => 'tiarakusuma@example.com',
                'no_hp' => '086789826360',
                'pekerjaan' => 'Software Developer',
                'instansi' => 'Data Insight Co.',
                'alamat' => 'Jl. Mawar No. 101, Bandung',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Zaki Rahman',
                'nim' => '2021101040',
                'prodi' => 'Informatika',
                'tahun_masuk' => 2021,
                'tahun_lulus' => 2025,
                'IPK' => 3.26,
                'email' => 'zakirahman@example.com',
                'no_hp' => '085887611409',
                'pekerjaan' => 'Data Analyst',
                'instansi' => 'Inovasi Digital Nusantara',
                'alamat' => 'Jl. Melati No. 181, Jakarta',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Rita Anggraini',
                'nim' => '2021101041',
                'prodi' => 'Informatika',
                'tahun_masuk' => 2021,
                'tahun_lulus' => 2025,
                'IPK' => 3.37,
                'email' => 'ritaanggraini@example.com',
                'no_hp' => '089309256183',
                'pekerjaan' => 'Database Administrator',
                'instansi' => 'Inovasi Digital Nusantara',
                'alamat' => 'Jl. Mawar No. 78, Jakarta',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Donny Hidayat',
                'nim' => '2021101042',
                'prodi' => 'Informatika',
                'tahun_masuk' => 2021,
                'tahun_lulus' => 2025,
                'IPK' => 3.98,
                'email' => 'donnyhidayat@example.com',
                'no_hp' => '087995458578',
                'pekerjaan' => 'Network Engineer',
                'instansi' => 'Solusi IT Global',
                'alamat' => 'Jl. Anggrek No. 153, Surabaya',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Astri Melati',
                'nim' => '2021101043',
                'prodi' => 'Sistem Informasi',
                'tahun_masuk' => 2021,
                'tahun_lulus' => 2025,
                'IPK' => 3.37,
                'email' => 'astrimelati@example.com',
                'no_hp' => '082782042123',
                'pekerjaan' => 'Software Developer',
                'instansi' => 'Data Insight Co.',
                'alamat' => 'Jl. Melati No. 114, Bandung',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Gilbert Sinaga',
                'nim' => '2021101044',
                'prodi' => 'Teknik Komputer',
                'tahun_masuk' => 2021,
                'tahun_lulus' => 2025,
                'IPK' => 3.83,
                'email' => 'gilbertsinaga@example.com',
                'no_hp' => '081761259088',
                'pekerjaan' => 'Database Administrator',
                'instansi' => 'Teknologi Mandiri',
                'alamat' => 'Jl. Anggrek No. 106, Surabaya',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Sari Melinda',
                'nim' => '2021101045',
                'prodi' => 'Teknik Komputer',
                'tahun_masuk' => 2021,
                'tahun_lulus' => 2025,
                'IPK' => 3.98,
                'email' => 'sarimelinda@example.com',
                'no_hp' => '086175331541',
                'pekerjaan' => 'System Administrator',
                'instansi' => 'Teknologi Mandiri',
                'alamat' => 'Jl. Mawar No. 70, Surabaya',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Iqbal Ramadhan',
                'nim' => '2021101046',
                'prodi' => 'Sistem Informasi',
                'tahun_masuk' => 2021,
                'tahun_lulus' => 2025,
                'IPK' => 3.12,
                'email' => 'iqbalramadhan@example.com',
                'no_hp' => '085641443220',
                'pekerjaan' => 'Database Administrator',
                'instansi' => 'Teknologi Mandiri',
                'alamat' => 'Jl. Mawar No. 156, Bandung',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Yulia Citra',
                'nim' => '2021101047',
                'prodi' => 'Informatika',
                'tahun_masuk' => 2021,
                'tahun_lulus' => 2025,
                'IPK' => 3.23,
                'email' => 'yuliacitra@example.com',
                'no_hp' => '087506681435',
                'pekerjaan' => 'Database Administrator',
                'instansi' => 'Solusi IT Global',
                'alamat' => 'Jl. Mawar No. 97, Bandung',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Tommy Prasetya',
                'nim' => '2021101048',
                'prodi' => 'Sistem Informasi',
                'tahun_masuk' => 2021,
                'tahun_lulus' => 2025,
                'IPK' => 3.03,
                'email' => 'tommyprasetya@example.com',
                'no_hp' => '084661260372',
                'pekerjaan' => 'Data Analyst',
                'instansi' => 'Data Insight Co.',
                'alamat' => 'Jl. Melati No. 98, Bandung',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Melisa Ayu',
                'nim' => '2021101049',
                'prodi' => 'Teknik Komputer',
                'tahun_masuk' => 2021,
                'tahun_lulus' => 2025,
                'IPK' => 3.49,
                'email' => 'melisaayu@example.com',
                'no_hp' => '084083459703',
                'pekerjaan' => 'Network Engineer',
                'instansi' => 'Teknologi Mandiri',
                'alamat' => 'Jl. Melati No. 99, Bandung',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Joko Priyono',
                'nim' => '2021101050',
                'prodi' => 'Sistem Informasi',
                'tahun_masuk' => 2021,
                'tahun_lulus' => 2025,
                'IPK' => 3.07,
                'email' => 'jokopriyono@example.com',
                'no_hp' => '085746695914',
                'pekerjaan' => 'Data Analyst',
                'instansi' => 'Solusi IT Global',
                'alamat' => 'Jl. Dahlia No. 143, Jakarta',
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ]);
    }
}
